export const REPORT_CREATE_REQUEST = "REPORT_CREATE_REQUEST";
export const REPORT_CREATE_SUCCESS = "REPORT_CREATE_SUCCESS";
export const REPORT_CREATE_FAILURE = "REPORT_CREATE_FAILURE";
export const REPORT_CREATE_RESET = "REPORT_CREATE_RESET";

export const REPORT_DETAILS_REQUEST = "REPORT_DETAILS_REQUEST";
export const REPORT_DETAILS_SUCCESS = "REPORT_DETAILS_SUCCESS";
export const REPORT_DETAILS_FAILURE = "REPORT_DETAILS_FAILURE";

export const REPORT_PAY_REQUEST = "REPORT_PAY_REQUEST";
export const REPORT_PAY_SUCCESS = "REPORT_DETAILS_SUCCESS";
export const REPORT_PAY_FAILURE = "REPORT_DETAILS_FAILURE";
export const REPORT_PAY_RESET = "REPORT_PAY_RESET";

export const REPORT_LIST_MINE_REQUEST = "REPORT_LIST_REQUEST";
export const REPORT_LIST_MINE_SUCCESS = "REPORT_LIST_SUCCESS";
export const REPORT_LIST_MINE_FAILURE = "REPORT_LIST_FAILURE";
